### ISSUE TITLE
Funciton ExCheck.GraphExecutor.run/2 is undefined.

### ISSUE THREAD

**Issue by brunoripa** [karolsluszniak/ex_check#4] opened 2019-09-09 12:17 UTC
Hi, i was using `analyze` to run the tests, but then i switched to `ex_check`; it was working nicely (i have adopted it in 2 or 3 microservices) but suddendly it started to be pretty unreliable and i don't understand why.

I was using `0.10.0`, so today I also updated to `0.11.0` but it keeps on failing with the following error.
```
** (UndefinedFunctionError) function ExCheck.GraphExecutor.run/2 is undefined (module ExCheck.GraphExecutor is not available)
    ExCheck.GraphExecutor.run([{:formatter, [], {:pending, {:formatter, "mix format --check-formatted", []}}}, {:credo, [], {:pending, {:credo, "mix credo --strict --format oneline", []}}}, {:sobelow, [], {:pending, {:sobelow, "mix sobelow --config", []}}}, {:ex_doc, [], {:pending, {:ex_doc, "mix docs", []}}}, {:ex_unit, [], {:pending, {:ex_unit, "mix test", []}}}], [parallel: true, start_fn: #Function<14.31308330/1 in ExCheck.Check.run_tools/2>, collect_fn: #Function<15.31308330/1 in ExCheck.Check.run_tools/2>])
    lib/ex_check/check.ex:52: ExCheck.Check.run_others/2
    lib/ex_check/check.ex:18: ExCheck.Check.compile_and_run_tools/2
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```

My pakcage deps are (one is redacted for privacy,, is a source package we developed):

```
      {:phoenix, "~> 1.4.9"},
      {:phoenix_pubsub, "~> 1.1"},
      {:phoenix_ecto, "~> 4.0"},
      {:ecto_sql, "~> 3.1"},
      {:postgrex, ">= 0.0.0"},
      {:gettext, "~> 0.11"},
      {:jason, "~> 1.0"},
      {:plug_cowboy, "~> 2.0"},

      # Dev
      {:ex_check, "~> 0.11", only: [:dev], runtime: false},
      {:credo, "~> 0.8", only: [:dev], override: true},
      {:ex_doc, "~> 0.21", only: [:dev], override: true},
      {:sobelow, "~> 0.8", only: [:dev]},
      {:excoveralls, "~> 0.11", only: [:dev, :test]}
```

**Comment by bitboxer** [comment] 2019-09-09 12:33
Can you provide your `.check.exs` File?

**Comment by karolsluszniak** [comment] 2019-09-09 13:26
@brunoripa This should be fairly easy to fix since I don't think the issue is on ex_check side. You see, the `ExCheck.GraphExecutor` module that the error refers to was renamed in v0.11.0 to `ExCheck.Pipeline`. You can see for yourself that in [v0.11.0 release dump](https://github.com/karolsluszniak/ex_check/archive/v0.11.0.zip) there's no reference to GraphExecutor across entire ex_check codebase.

Therefore it seems like you somehow ended up with ex_check v0.10.0 build artifact that can no longer build the module that was needed in that version because you've upgraded to v0.11.0. You should start by cleaning the ex_check build (`mix deps.clean ex_check`) and if that won't help just remove the entire `_build` directory.

I've seen such issues come up especially in umbrella projects which inconsistently declare/forget to declare same dependency across child apps or the root project. Don't know the exact reason why it pops up though.

---

Btw, by `analyze` do you mean https://github.com/IanLuites/analyze? I haven't seen it before. How was it working for you? Looks like a very, very young project with no docs to explain what it does... Perhaps if it's useful for most projects & once it matures it's a future candidate for including in curated tools for ex_check.

**Comment by brunoripa** [comment] 2019-09-18 06:24
Hi @karolsluszniak , sorry for the late reply. I got your suggestion, i will try today ! About analyze, you are basically right that it's lacking a better doc etc., but basically it runs a bunch of tools up to dialyzer, so there's some overlapping here and definitely there might be some interesting changes to "cooperate" i guess.

**Comment by IanLuites** [comment] 2019-09-18 09:01
Hey author of analyze here.

It's mostly an private / company dependency that reports the status of each check to whatever.

We use it to pass/fail checks in git. Created it years ago, intention of improving it, never had the time.

**Comment by karolsluszniak** [comment] 2019-10-25 09:10
Closing the issue as I was easily able to reproduce it and confirm that `mix deps.clean ex_check` indeed solves the problem which indeed lies in build caching.

**Closed by karolsluszniak** 2019-10-25 09:10 UTC
