### ISSUE TITLE
Feature request: add JS tests

### ISSUE THREAD

**Issue by bitboxer** [karolsluszniak/ex_check#2] opened 2019-08-08 19:23 UTC
It would be amazing if `mix check` would also run the tests of the javascript part of an phoenix app. Would you love to have a PR for this?

**Comment by bitboxer** [comment] 2019-08-08 19:32
To make it clear: I know that I can add that config myself, but we could check for the existence of a test command in the package json and use that.

**Comment by karolsluszniak** [comment] 2019-08-09 11:54
@bitboxer I’m glad to see this feature request because indeed I have it on the agenda, so it’s nice to see it anticipated. 

Currently I’m focusing on bringing cross-tool dependencies (already landed on master) and using that for validating test coverage. Seamless & automated execution of `npm test` (along with possibly for including other JS checking tools) in Phoenix project will come right after.

There are a few blockers though that I need to figure out & remove before this will be possible in quality & bug-free way. To be specific:

1. Phoenix projects may be generated in a form of umbrella projects. In such projects, `mix check` may be run in root of the project or in specific app. Now, the expected behaviour with `npm test` would be to execute it for specific Phoenix app if you’re in its directory, to ignore it for app without `assets` and to run it for all viable apps if `mix check` is run in umbrella root. This is currently not possible, but will be after extending ex_check with an equivalent of `Mix.Task`’s `recursive` option.

2. Curated tools aim to be viable default for any Elixir project, not just Phoenix project - and should be advertised via messages about skipped tools to hint possible toolset expansion. `npm test` for `assets` subdirectory is strictly Phoenix-centric and as such I wouldn’t want this tool to be hinted for non-Phoenix projects. This is currently not possible and I’ll have to figure out a clean way for missing curated tool requirements to sometimes show hints and sometimes not.

3. If we were to indeed run the check if `test` script is configured in `package.json` and skip otherwise, then ex_check would have to start understanding `package.json` which it currently also doesn’t (or use another means for ensuring that out of the box tool may be run). I see this as a worthwhile extension for sake of Phoenix users but it’s also not there yet.

If you feel like tackling these challenges, I’m happy to see a PR. Project still lacks contributing guide and code of conduct (I hope to add them soon) so we may have to do some alignments on your code but I don’t see this as a PR blocker.

**Comment by bitboxer** [comment] 2019-08-12 07:54
Awesome. That sounds like you already have a plan how to refactor the app to make this possible. Can you open tickets for each and explain how you would love these things to be implemented? Then I would pick one and start from there :) .

**Comment by karolsluszniak** [comment] 2019-09-08 07:58
I'm happy to report that the addition of including `npm test` for Phoenix projects has yesterday landed on master (merged from #3) and released as part of [v0.11.0](https://github.com/karolsluszniak/ex_check/blob/master/CHANGELOG.md#v0110).

As promised, it works just as well in regular and umbrellized Phoenix projects. And actually any Elixir projects that have JS assets with `package.json` in `assets` directory, which can be easily reconfigured to target different directory via `{:npm_test, cd: "other_dir"}` in `.check.exs`. And if one would have more than one web app with assets in an umbrella, it'll hand-pick them and execute `npm test` for all of them in parallel.

Btw I've decided to proceed with this one on my own considering the vast scope of changes and batches of refactors required for making this one happen without making the library code harder to maintain.

Thanks for pushing this one forward and ofc please let me know in case of any problems.

**Closed by karolsluszniak** 2019-09-08 07:58 UTC

**Comment by bitboxer** [comment] 2019-09-08 18:41
Thank you for your hard work on this!
